# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: ""

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: ""

- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: 'Visual Studio Enterprise(6bba67a2-8699-485b-852b-41f1de66d12c)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob delete-batch --account-name parkerbibusportfolio --source $web'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular/parkerbibusportfolio'
    targetPath: 'dist'


- task: AzureFileCopy@3
  inputs:
    SourcePath: 'dist/parker-bibus-portfolio'
    ConnectedServiceNameARM: 'Visual Studio Enterprise(6bba67a2-8699-485b-852b-41f1de66d12c)'
    Destination: 'AzureBlob'
    StorageAccountRM: 'parkerbibusportfolio'
    ContainerName: '$web'
