# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: ""

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: ""

# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'angular/parkerbibusportfolio'
#     targetPath: 'dist'


- task: AzureFileCopy@3
  inputs:
    SourcePath: 'dist/parker-bibus-portfolio'
    ConnectedServiceNameARM: 'Pay-As-You-Go(27004a44-c36f-4c1e-a0c2-ff39eba21f1b)'
    Destination: 'AzureBlob'
    StorageAccountRM: 'parkerbibusportfolio'
    ContainerName: '$web'
    cleanTargetBeforeCopy: true